= BDR Catalogues
:table-stripes: even
:sectnums:

This document contains some of the static (file-based) content for the https://www.dcceew.gov.au/environment/environment-information-australia/biodiversity-data-repository[Biodiversity Data Repository], as seen online at https://resources.bdr.gov.au/catalogues in the Datasets, Models & Validators catalogues.

It does not contain the dynamic data of the BDR Datasets catalogue itself nore does it contain the Vocabularies catalogue information which is stored in https://github.com/dcceew-bdr/bdr-vocabs.

== Catalogue Data

The data in this repository which comprises both data and metadata for the above listed catalogues is stored as https://en.wikipedia.org/wiki/Resource_Description_Framework[RDF] data files.

The `master` folder and its sub-folders with a `catalogue.ttl` file in them represent a catalogue with the cataloge metadata in the file. Items in the catalogue - which may be other catalogues or Datasets, Models or Validators, are stored in subfolders.

The `background` folder contains labelling files for all catalogues and items.

The `manifest.ttl` file in the top directory of this repository lists all content and is are created according to the https://prez.dev/manifest/[Prez Manifest Model] and can be used to synchronise these catalogues with RDF databases using the https://github.com/Kurrawong/prezmanifest[PrezManifest] tool.

== Rights and License

Content generated by the Department of Climate Change, Energy, the Environment and Water (DCCEEW) is copyright as follows:

&copy; Commonwealth of Australia, 2025

This information is available for reuse under the https://creativecommons.org/licenses/by/4.0/[Creative Commons 4.0 license], see the LICENSE file for the deed.

== Contacts

For all enquiries, please contact:

*BDR Team* +
bdr@dcceew.gov.au
